VERSION="1.0.2"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBEAPUJKWP32U4HXGTSKJ4NPVBYY5JEKUBFWHSL7OUZGF4EZWACVM7W4",
"GAJI22CBXERRYLK2VPIN3JBZXTLTP4YRKW662YSRHDOXT4M7SOFCAMXK"
]

[DOCUMENTATION]
ORG_NAME="XLM LIQUIDITY"
ORG_LOGO="https://xlmliquidity.io/images/logo.png"
ORG_DESCRIPTION="Providing liquidity to several projects on Stellar blockchain."

[[CURRENCIES]]
code="xlmLIQUIDITY"
issuer="GBEAPUJKWP32U4HXGTSKJ4NPVBYY5JEKUBFWHSL7OUZGF4EZWACVM7W4"
display_decimals=7
name="XLM Liquidity"
desc="Providing liquidity to several projects on Stellar blockchain."
conditions="10,000,000,000 issued"
image="https://xlmliquidity.io/images/logo.png"

